version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:12

jobs:
  setup:
    executor: my-executor
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "package-lock.json" }}
          paths:
             - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  unit:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: yarn-packages-{{ checksum "package-lock.json" }}
      - run: yarn run unit:coverage

  build:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: yarn-packages-{{ checksum "package-lock.json" }}
      - run: yarn run build

workflows:
  app:
    jobs:
      - setup
      - unit:
          requires:
            - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              only: master