version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  unit:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn run unit:coverage

  build:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn run build

workflows:
  app:
    jobs:
      - setup
      - unit:
          requires:
            - setup
      - build:
          requires:
            - setup