version: 2

defaults: &defaults
  docker:
    - image: circleci/node:12.16.0

regviz: &regviz
  docker:
    - image: regviz/node-xcb

step_restore_cache: &restore_cache
  restore_cache:
    keys:
    - v1-dependencies-{{ checksum "yarn.lock" }}-1
    - v1-dependencies-

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn --frozen-lockfile

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-dependencies-{{ checksum "yarn.lock" }}-1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: yarn lint:ts
      - run: yarn lint:css
      - run: yarn tsc
      - run: yarn test:coverage

  storybook:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: yarn storybook:build
      - store_artifacts:
          path: ./storybook-static

  regression:
    <<: *regviz
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: yarn storycap
      - run: yarn regression


workflows:
  version: 2
  ci:
    jobs:
      - test
      - storybook
      - regression:
          filters:
            branches:
              only: master
