version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:12.13.0
  regviz-executor:
    docker:
      - image: regviz/node-xcb

jobs:
  setup:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
             - node_modules

  unit:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: npm run test:coverage

  regression:
    executor: regviz-executor
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn storycap
      - run: yarn regression

workflows:
  app:
    jobs:
      - setup
      - unit:
          requires:
            - setup
      - regression:
          requires:
            - setup
          filters:
            branches:
              only: master
