/**
 * Application theme color
 */
const THEME_COLOR = {
  BLACK: '#0d0d0d',
  SKY_BLUE: '#7ebcf2',
  HORIZON_BLUE: '#5ed7f2',
  NILE_GREEN: '#05f2db',
  PEER_AQUA: '#7ef2e7'
}

/**
 * Base color
 */
const BASE_COLOR = {
  WHIET: '#fff',
  SILVER: '#ccc',
  GLAY: '#818a91',
  BRIGHT_GLAY: '#f7f7f7',
  IRON_BLACK: '#20232a',
  DARK_GLAY: '#282c34',
  WHITE_GLAY: '#e5e5e5',
  RED: '#cd3d64',
  ALPHA_GLAY: 'rgba(0,0,0,0.54)'
}

/**
 * Text color
 */
export const COLOR = {
  BLACK: THEME_COLOR.BLACK,
  WHITE: BASE_COLOR.WHIET,
  RED: BASE_COLOR.RED,
  HORIZON_BLUE: THEME_COLOR.HORIZON_BLUE,
  GLAY: BASE_COLOR.GLAY,
  DARK_GLAY: BASE_COLOR.DARK_GLAY
}

/**
 * Backgruond color
 */
export const BACKGROUND_COLOR = {
  WHITE: BASE_COLOR.WHIET,
  RED: BASE_COLOR.RED,
  SILVER: BASE_COLOR.SILVER,
  GLAY: BASE_COLOR.GLAY,
  BRIGHT_GLAY: BASE_COLOR.BRIGHT_GLAY,
  DARK_GLAY: BASE_COLOR.DARK_GLAY,
  WHITE_GLAY: BASE_COLOR.WHITE_GLAY,
  IRON_BLACK: BASE_COLOR.IRON_BLACK,
  SKY_BLUE: THEME_COLOR.SKY_BLUE,
  HORIZON_BLUE: THEME_COLOR.HORIZON_BLUE
}

/**
 * Border color
 */
export const BORDER_COLOR = {
  WHITE: BASE_COLOR.WHIET,
  RED: BASE_COLOR.RED,
  SILVER: BASE_COLOR.SILVER,
  WHITE_GLAY: BASE_COLOR.WHITE_GLAY,
  HORIZON_BLUE: THEME_COLOR.HORIZON_BLUE
}

/**
 * break point
 */

export const BREAK_POINT = {
  MOBILE: 750,
  TABLET: 1024
}
