name: Github Action Test
on:
  push:
    branches:
      - master
    tags:
      - "!*"


jobs:
  test:
    name: GitHub Context
    runs-on: macOS-latest
    steps:
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"