name: Release

on:
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output variables
        id: vars
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: title
          branch: master
          base: ${{ steps.vars.outputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

