name: Release

on:
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ""
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: title
          branch: ${GITHUB_REF#refs/heads/}
          token: ${{ secrets.GITHUB_TOKEN }}

