name: Release

on:
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output variables
        id: vars
        run: |
          echo "::set-output name=pr_title::Release $(date +%d-%m-%Y)"
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ steps.vars.outputs.pr_title }}
          base: master
          branch: ${{ steps.vars.outputs.branch }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
